import Coffee from './Coffee.js'

function App() {
  return (
    <>
    <Coffee />
   </>
  );
}

export default App;


// NOTE: CAPITALISE THE FILE NAME FIRST LETTER, AND THE COMPONENTS AS WELL TO RUN WITHOUT WARNINGS AND RUN SUCESSFULLY.
// IF HTML IS RETURNED THEN FILE NAMED JSX 
// IF HTML IS NOT RETURNED THEN FILE NAMED AS JS , ONLY JS CODE WRITTEN.
// IN VITE-PROJECT, CONVENTION IS THAT FILE NAME SHOULD BE JSX .